// This file will be generated by Supabase CLI
// Run: supabase gen types typescript --linked > types/database.ts
// Or copy from your existing project

// Placeholder types - replace with actual generated types
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      contract_templates: {
        Row: {
          id: string
          name: string
          description: string | null
          content: Json
          variables: Json | null
          created_by: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          content?: Json
          variables?: Json | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          content?: Json
          variables?: Json | null
          created_by?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
      }
      contracts: {
        Row: {
          id: string
          template_id: string | null
          name: string
          description: string | null
          content: Json
          variable_values: Json | null
          fillable_field_values: Json | null
          status: 'draft' | 'final' | 'archived'
          created_by: string | null
          created_at: string
          updated_at: string
          finalized_at: string | null
          deleted_at: string | null
        }
        Insert: {
          id?: string
          template_id?: string | null
          name: string
          description?: string | null
          content?: Json
          variable_values?: Json | null
          fillable_field_values?: Json | null
          status?: 'draft' | 'final' | 'archived'
          created_by?: string | null
          created_at?: string
          updated_at?: string
          finalized_at?: string | null
          deleted_at?: string | null
        }
        Update: {
          id?: string
          template_id?: string | null
          name?: string
          description?: string | null
          content?: Json
          variable_values?: Json | null
          fillable_field_values?: Json | null
          status?: 'draft' | 'final' | 'archived'
          created_by?: string | null
          created_at?: string
          updated_at?: string
          finalized_at?: string | null
          deleted_at?: string | null
        }
      }
      contract_versions: {
        Row: {
          id: string
          contract_id: string
          content: Json
          variable_values: Json | null
          fillable_field_values: Json | null
          version_number: number
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          contract_id: string
          content?: Json
          variable_values?: Json | null
          fillable_field_values?: Json | null
          version_number: number
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          contract_id?: string
          content?: Json
          variable_values?: Json | null
          fillable_field_values?: Json | null
          version_number?: number
          created_by?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
